### ISSUE TITLE
Grammarly Listed Twice

### ISSUE THREAD

**Issue by liamzee** [clojurists-together/clojuriststogether.org#224]
**Describe the bug**
Grammarly listed twice

**To Reproduce**
curl https://www.clojuriststogether.org/members/

**Expected behavior**
Grammarly listed once

**Screenshots**

**Desktop (please complete the following information):**
Arch Linux - Vivaldi

**Additional context**

**Comment by danielcompton** [comment]
Thanks, this should be fixed in a few minutes.
